blank_issues_enabled: false
contact_links:
  - name: Contributing Guide
    url: https://github.com/UCBerkeleySETI/blipss/blob/main/CONTRIBUTING.md
    about: Read the contributing guidelines before opening an issue or pull request.
