# Produce a plot of a phase-resolved spectrum for a given folding period.

input_data:
  datafile: guppi_58704_86381_BLGCsurvey_Cband_B04_0014.gpuspec.0002.fil  # Name of Blimpy-readable data file
  data_dir: /home/ella1/asuresh/SETI/Real_data  # Path to above data file

output:
  basename: B04_58704_0014  # Basename of output plot
  plot_formats: null  # List of output plot formats (d: ['.png'])
  plot_dir: /home/ella1/asuresh/SETI/Phase_ds  # Output path (d: data_dir)

channel_selection:
  start_ch: 288673  # All channels with indices less than this integer value will be ignored. (d: 0)
  stop_ch: 1484096  # All channels with indices larger than or equal to this integer value will be ignored. (d: len(data))

phase_folding_parameters:
  period: 21.51049  # Folding period (s) (d: 1.0)
  bins: 11  # No. of bins desired across folded profile (d: 10)
  do_deredden: true  # Do you want to deredden the time series before searching? (True/False) (d: False)
  rmed_width: null  # Width (s) of running median filter used for dereddening. Set width > max_period/bins_min. (d: 12.0)

resource_limits:
  mem_load: 15.0  # Max data volume (GB) allowed to be read into memory (d: 1)
